[package]
name = "primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
byteorder = { workspace = true }
rand = { workspace = true }
memmap2 = { workspace = true }
bincode = "1.3"

[lib]
name = "primitives"
path = "src/main.rs"