[workspace]
members = [
    "lib",
    "program",
    "script",
    "primitives",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
byteorder = "1.4.3"
rand = "0.8.5"
memmap2 = "0.5.3"